import * as maplibregl from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import workerUrl from 'maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url';
import {land} from '../../src/assets/land.ts';
import {buildTrip} from '../../src/fixtures/travel.ts';
import {groupPoints,pointsFromTimeline,shortlist} from '../../src/experiments/landmark.ts';
import './style.css';
const provider=__PROVIDER__, title=provider==='maptiler'?'MapTiler':'Geoapify';
document.querySelector('#root').innerHTML=`<header><div><small>FOOTPRINT GLOBE · 실험용 프리뷰</small><h1>${title} 랜드마크 비교</h1></div><nav><a href='/maptiler/'>MapTiler</a><a href='/geoapify/'>Geoapify</a></nav></header><main><aside><label for='trip'>가상 여행 선택</label><select id='trip'><option value='austria'>오스트리아</option><option value='france'>프랑스</option><option value='italy'>이탈리아</option><option value='japan'>일본</option></select><p id='summary'></p><button id='mock'>가상 응답 시험</button><button id='live' disabled>실제 API 조회</button><p id='status' role='status'>설정 확인 중</p><p id='quota'></p><h2>비교 지점</h2><ol id='groups'></ol><details><summary>시험 기준과 한계</summary><p>연속 관측을 첫 점 기준 100m 이내로 묶습니다. 120분 넘는 공백은 별도 묶음입니다. 10분 이상 머문 묶음 중 최대 8개 대표 지점을 조회합니다. 제품 정책으로 확정된 기준은 아닙니다.</p><p>${provider==='maptiler'?'일반 POI 역검색 최대 10개 중 300m 이내만 표시합니다. 상점 등이 포함될 수 있습니다.':'관광 명소·관광 볼거리·박물관을 반경 300m에서 최대 10개 검색합니다.'}</p><p>검색 범주가 다르므로 결과 개수만으로 우열을 판단하지 않습니다. 주변 후보는 방문 사실을 뜻하지 않습니다.</p></details></aside><section class='map-wrap'><div id='map'></div><div class='map-note'>로컬 개략 지도 · 선은 가상 관측 연결<br>초록: 묶음 / 주황: 비교 지점 · 상세 지도 없음</div></section><aside><h2 id='result-title'>주변 랜드마크 후보</h2><p id='mode'>아직 조회하지 않았습니다.</p><div id='results'></div><footer>지도: Natural Earth<br>검색: <a href="https://www.geoapify.com/" target="_blank" rel="noreferrer">Geoapify</a> / <a href="https://www.maptiler.com/" target="_blank" rel="noreferrer">MapTiler</a><br>© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap contributors</a></footer></aside></main>`;
const el=id=>document.getElementById(id);
let points=[],groups=[],samples=[],results=new Map(),mode='',selected=0,revision=0,controller,configured=false,popup;
maplibregl.setWorkerUrl(workerUrl);
const map=new maplibregl.Map({container:'map',center:[16,48],zoom:5,attributionControl:false,style:{version:8,sources:{land:{type:'geojson',data:{type:'FeatureCollection',features:land}}},layers:[{id:'water',type:'background',paint:{'background-color':'#dcebf0'}},{id:'land',type:'fill',source:'land',paint:{'fill-color':'#f2f1e8'}}]}});
map.addControl(new maplibregl.NavigationControl());
const collection=features=>({type:'FeatureCollection',features});
function draw(){if(!map.getSource('route'))return;map.getSource('route').setData({type:'Feature',properties:{},geometry:{type:'LineString',coordinates:points.map(p=>[p.lon,p.lat])}});for(const [name,items] of [['groups',groups],['samples',samples]])map.getSource(name).setData(collection(items.map((g,i)=>({type:'Feature',properties:{index:i},geometry:{type:'Point',coordinates:[g.point.lon,g.point.lat]}}))));const bounds=new maplibregl.LngLatBounds();points.forEach(p=>bounds.extend([p.lon,p.lat]));map.fitBounds(bounds,{padding:55,duration:0,maxZoom:13});}
function render(){el('result-title').textContent=`비교 지점 ${selected+1}`;el('mode').textContent=mode==='mock'?'가상 응답 · 실제 명소가 아닙니다':mode==='live'?'실제 API 응답 · 방문 여부 미확정':'아직 조회하지 않았습니다.';el('results').replaceChildren();const list=results.get(selected);if(!list){el('results').textContent='조회 버튼을 눌러 확인하세요.';return;}if(!list.length)el('results').textContent='반경 300m 내 이름이 있는 후보 없음';for(const place of list){const card=document.createElement('article'),name=document.createElement('strong'),info=document.createElement('p');name.textContent=place.name;info.textContent=`약 ${place.meters}m · ${place.category}`;card.append(name,info);el('results').append(card);}}
function select(i){selected=i;render();popup?.remove();const g=samples[i];if(!g)return;const content=document.createElement('div'),name=document.createElement('strong'),info=document.createElement('p');name.textContent=(mode==='mock'?'[가상] ':'')+(results.get(i)?.[0]?.name||`비교 지점 ${i+1}`);info.textContent=`${g.count}개 관측 · 약 ${Math.round((g.end-g.start)/60000)}분`;content.append(name,info);popup=new maplibregl.Popup().setLngLat([g.point.lon,g.point.lat]).setDOMContent(content).addTo(map);map.easeTo({center:[g.point.lon,g.point.lat],zoom:15});}
function load(){revision++;controller?.abort();popup?.remove();points=pointsFromTimeline(buildTrip(el('trip').value).timeline);groups=groupPoints(points);samples=shortlist(groups);results=new Map();mode='';selected=0;el('summary').textContent=`관측 ${points.length.toLocaleString()}개 → 묶음 ${groups.length.toLocaleString()}개 · 비교 ${samples.length}곳`;el('groups').replaceChildren();samples.forEach((g,i)=>{const li=document.createElement('li'),button=document.createElement('button');button.textContent=`지점 ${i+1} · ${Math.round((g.end-g.start)/60000)}분 · ${g.count}개`;button.onclick=()=>select(i);li.append(button);el('groups').append(li);});el('live').disabled=!configured;el('mock').disabled=false;el('status').textContent='가상 여행 준비 완료';render();draw();}
map.on('load',()=>{for(const name of ['route','groups','samples'])map.addSource(name,{type:'geojson',data:collection([])});map.addLayer({id:'route',type:'line',source:'route',paint:{'line-color':'#3d829b','line-width':2}});map.addLayer({id:'groups',type:'circle',source:'groups',paint:{'circle-radius':3,'circle-color':'#367258'}});map.addLayer({id:'samples',type:'circle',source:'samples',paint:{'circle-radius':7,'circle-color':'#c66b26','circle-stroke-width':2,'circle-stroke-color':'white'}});map.on('click','samples',e=>select(Number(e.features[0].properties.index)));draw();});
el('trip').onchange=load;
el('mock').onclick=()=>{mode='mock';results=new Map(samples.map((g,i)=>[i,[{name:`가상 명소 ${i+1}`,meters:12,category:'합성 관광지'}]]));el('status').textContent='가상 응답 시험 완료 · 외부 조회 없음';select(0);};
el('live').onclick=async()=>{const rev=++revision;controller?.abort();controller=new AbortController();mode='live';results=new Map();popup?.remove();render();el('live').disabled=true;el('mock').disabled=true;try{for(let i=0;i<samples.length;i++){el('status').textContent=`실제 조회 중 ${i+1}/${samples.length}`;const response=await fetch(`/api/places?provider=${provider}&trip=${el('trip').value}&index=${i}`,{signal:controller.signal});const data=await response.json();if(rev!==revision)return;if(data.used!==undefined)el('quota').textContent=`서버 실행 이후 API 요청 ${data.used}/32회`;if(!response.ok){el('status').textContent=`조회 중단: ${data.code}`;return;}results.set(i,data.places);render();}el('status').textContent=`실제 조회 완료 · ${results.size}곳 · 후보 ${[...results.values()].reduce((n,p)=>n+p.length,0)}개`;select(0);}catch{if(rev===revision)el('status').textContent='조회 중단: LOCAL_REQUEST_FAILED';}finally{if(rev===revision){el('live').disabled=!configured;el('mock').disabled=false;}}};
load();fetch('/api/status').then(r=>r.json()).then(data=>{configured=!!data.configured?.[provider];el('live').disabled=!configured;el('status').textContent=configured?'키 설정 확인 · 실제 조회 가능':'키 미설정 · 가상 응답 시험 가능';el('quota').textContent=`서버 실행 이후 API 요청 ${data.used?.[provider]||0}/32회`;}).catch(()=>{el('status').textContent='로컬 서버 설정 확인 실패';});
window.addEventListener('pagehide',()=>{controller?.abort();map.remove();});
